# Site settings
title: Alec Belliveau
description: A pretty cool guy you should definetly hire
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://alecbelliveau.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alec Belliveau
user_description: I'm a recent Electrical/Computer Engineering graduate from the University of New Brunswick flexible in both high level and low level programming, as well as hardware implementations. I'm Equally interested in non-emitting energy generation, nuclear being the most fascinating. I'm currently looking for my next employment opportunity, So be sure to reach out if you're interested.
user_title: Electrical Engineer
email: arbelliveau@live.com
twitter_username: lorem_ipsum
github_username:  AlecBelliveau
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
